repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict

  # TODO: enable ruff
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.16.10
  #   hooks:
  #     - id: ruff-check
  #       args: [--target-version=py37]
  #     - id: ruff-format

  # TODO: enable ty
  #- repo: https://github.com/astral-sh/ty-pre-commit
  #  rev: v0.0.84
  #  hooks:
  #    - id: ty
  #      args: [--group=typechecking]

  # TODO: enable standard
  # - repo: https://github.com/standard/standard
  #   rev: v17.1.2
  #   hooks:
  #     - id: standard

    # TODO: enable djlint
  # - repo: https://github.com/djlint/djLint
  #   rev: v1.46.4
  #   hooks:
  #     - id: djlint-reformat-jinja
  #     - id: djlint-jinja

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell
        additional_dependencies:
        - tomli
