[build-system]
requires = [
    "setuptools>=68",
]
build-backend = "setuptools.build_meta"

[project]
name = "OctoPrint-Enclosure"
version = "4.13.2"
description = "Awesome plugin to control everything that you ever wanted on your enclosure"
authors = [
    { name = "Jacopo Tediosi", email = "jacopotediosi@gmail.com" },
    { name = "Vitor Henrique", email = "vitormhenrique@gmail.com" },
]
requires-python = ">=3.7,<4"
dependencies = [
    "Adafruit-Blinka",  # for microcontroller.Pin used by DHT sensors
    "adafruit-circuitpython-dht>=3.5.0",  # min is 3.5.0 for adafruit_dht.exit()
    "bme680>=1.1.0",  # versions before 1.1.0 are broken
    "gpiozero>=1.5.0,!=2.0",  # for gpiozero.CPUTemperature; versions before 1.5.0 and 2.0 are broken
    "requests",
    "RPi.bme280>=0.2.0",  # min is 0.2.0 for the compensation_params in sample() signature
    "RPi.GPIO>=0.5.11",  # min is 0.5.11 for GPIO.getmode()
    "smbus2>=0.3.0",  # min is 0.3.0 for SMBus as context manager
    "spidev",
]
dynamic = [
    "license",
]

[project.entry-points."octoprint.plugin"]
enclosure = "octoprint_enclosure"

[project.urls]
Homepage = "https://github.com/jacopotediosi/OctoPrint-Enclosure"

[project.optional-dependencies]
develop = [
    "go-task-bin",
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = [
    "octoprint_enclosure",
    "octoprint_enclosure.*",
]
